### ISSUE TITLE
chore: Add Partykit as part of the deployment.

### ISSUE THREAD

**Issue by nickytonline** [nickytonline/astro-partykit-starter#10]
1. Run `npx partykit@latest token generate` to generate a token.
2. Run `ntl env:set PARTYKIT_LOGIN nickytonline` to add it to the environment variables for Netlify deploys.
3. Run `ntl env:set PARTYKIT_TOKEN THE_GENERATED_SUPER_SECRET_TOKEN` to add it to the environment variables for Netlify deploys.
4. Run `ntl env:set PUBLIC_PARTYKIT_HOST https://astro-partykit-starter-party.nickytonline.partykit.dev` so that the production URL for Partykit is available for the deployment.
5. Need to run `partykit deploy` as part of the deployment.

https://github.com/nickytonline/astro-partykit-starter/blob/f8f7cbb7d9f52c0d861e0027ef67661bffb1a6a7/package.json#L8

```diff
-  "build": "astro check && astro build",
+  "build": "astro check && astro build && partykit deploy",
```

6. Update the code for getting the Partykit URL to the following in https://github.com/nickytonline/astro-partykit-starter/blob/f8f7cbb7d9f52c0d861e0027ef67661bffb1a6a7/src/components/Party.tsx#L5

```diff
- const host = import.meta.env.PUBLIC_PARTYKIT_HOST ?? "localhost:1999";
+ const isProd = import.meta.env.PROD;
+ const host = isProd ? import.meta.env.PUBLIC_PARTYKIT_HOST : "localhost:1999";
```

**Comment by nickytonline** [comment]
I've already done steps 1-4 as they are CI/CD changes that don't involve code changes. I'll get to steps 5 and 6 in the next few days unless @adiati98, you'd like to make those changes. If so, feel free to assign yourself and unassign me.

**Comment by adiati98** [comment]
Taking it over, @nickytonline. 👍
