### ISSUE TITLE
docs: Document deployment process for Netlify and Partykit.

### ISSUE THREAD

**Issue by nickytonline** [nickytonline/astro-partykit-starter#11]
Based off of #10, we need to document the deployment process.

Setting up environment variables:

1. Run `npx partykit@latest token generate` to generate a token.
2. Run `ntl env:set PARTYKIT_LOGIN nickytonline` to add it to the environment variables for Netlify deploys.
3. Run `ntl env:set PARTYKIT_TOKEN THE_GENERATED_SUPER_SECRET_TOKEN` to add it to the environment variables for Netlify deploys.
4. Run `ntl env:set PUBLIC_PARTYKIT_HOST https://astro-partykit-starter-party.nickytonline.partykit.dev` so that the production URL for Partykit is available for the deployment.

Deployment to Netliffy:

Point to Netlify deployment docs (maybe this one https://www.netlify.com/blog/2016/09/29/a-step-by-step-guide-deploying-on-netlify/) and also using the Netlify CLI for deployments.

Partykit deployment:

This is handled once #10 is closed, but it'd be good to mention the Partykit deployment docs at https://docs.partykit.io/guides/deploying-your-partykit-server.

**Comment by nickytonline** [comment]
This doesn't necessarily have to be core team work, but leaving it for our new maintainers for now.

**Comment by jdwilkin4** [comment]
Hey @nickytonline ! 

I will be busy with freeCodeCamp stuff this week but if this issue is still open the following week, I'll be available to work on it

**Comment by nickytonline** [comment]
Cool, cool. I'll assign it to you and feel free to pick it up once you have time.
