### ISSUE TITLE
docs: Comment out instructions and add heading 2 to the issue form templates

### ISSUE THREAD

**Issue by adiati98** [nickytonline/astro-partykit-starter#14]
## Description

Currently, the instructions to fill out the issue forms are not commented out.
If contributors don't delete them when filling out the form, it would be hard for maintainers to review the issues.

Below are screenshots to the preview mode of the current issue form templates:

### Bug Issue

![nick - bug issue form](https://github.com/nickytonline/astro-partykit-starter/assets/45172775/6ab9d41c-a0a1-4740-bdfb-3106fdc79267)

### Feature Issue

![nick- feature issue form](https://github.com/nickytonline/astro-partykit-starter/assets/45172775/2163a9d3-48a3-46cc-b5a9-688f3e31aeb3)

## Suggested Solution

- Comment out the instructions to fill the forms.
- Make the bold titles as `h2` for better read and clarity.

**Comment by adiati98** [comment]
@nickytonline I self-assigned myself to this issue.
But I'll wait for your confirmation before working on it. Thanks! 😊

**Comment by nickytonline** [comment]
These are the default templates from GitHub that got generated. Feel free to improve them and the the team can discuss the changes.
