### ISSUE TITLE
Bug: Can't run multiple npm scripts after running `npm run dev`

### ISSUE THREAD

**Issue by adiati98** [nickytonline/astro-partykit-starter#22]
## Describe the bug

After setting up the local environment, I had trouble running multiple npm scripts with `npm run dev` either on Powershell or Git Bash. More details of the bug were discussed in PR #12.

## Suggested Solutions

Using `concurrently` package to run multiple npm scripts in parallel. Adding the package will enable contributors across platform to run the project and to contribute.

_Originally posted by @nickytonline in https://github.com/nickytonline/astro-partykit-starter/issues/12#issuecomment-1873311092_

## Steps to reproduce

1. Open VS Code on Windows machine.
2. On the terminal, choose Powershell or Git Bash if you have it installed.
3. After installing the dependencies, run `npm run dev`.
4. Only one script is executed as screenshot below:

    ![npm run dev warning 1](https://github.com/nickytonline/astro-partykit-starter/assets/45172775/f0ab7a71-ddbd-4810-a314-c9bddd8236d3)

## Expected behavior

After executing `npm run dev`, `astro dev` and `partykit dev` scripts should run and we should be able to preview the page locally, submit inputs, and print them out on the page.

## Desktop details

- OS: Windows 11

**Comment by jdwilkin4** [comment]
I have used `concurrently` in the past and it worked well for me

Tested this locally and this command should work

```
 "dev": "concurrently \"partykit dev\" \"astro dev\"",
```
<img width="1238" alt="Screenshot 2024-01-04 at 6 07 13 AM" src="https://github.com/nickytonline/astro-partykit-starter/assets/67210629/b086db2c-dc81-4fff-be06-7201fc559468">


also, if we wanted to have the local server start and open the browser window automatically, these command should work


```
    "open": "(sleep 3 & open http://localhost:4321/) || (timeout /nobreak /t 3 && start http://localhost:4321/)",
    "dev": "concurrently \"partykit dev\" \"astro dev\" \"npm run open\"",
```

**Comment by adiati98** [comment]
Thanks, @jdwilkin4 !

Just to confirm, are you using Mac?

I'll work on this and will test it out on Windows, too. 😊

**Comment by jdwilkin4** [comment]
Yes, I am on a mac. Concurrently should work for windows too

**Comment by Satoshi-Sh** [comment]
That's a great solution. I just tested it on Linux. :+1:

**Comment by adiati98** [comment]
I tested it out, and `open` command doesn't automatically open the browser window automatically on Windows.

According to [this thread](https://github.com/coryhouse/react-slingshot/issues/350), specifically [this comment](https://github.com/coryhouse/react-slingshot/issues/350#issuecomment-446918056), Mac is using `open` and Windows is using `start`.

I tested to copy the same line for `start` as below:

```bash
"start": "(sleep 3 & open http://localhost:4321/) || (timeout /nobreak /t 3 && start http://localhost:4321/)",
```

but it doesn't open the window automatically. I still needed to open the localhost manually. But it works!


So, I'll make the changes as @jdwilkin4 suggested, and will add something in the docs for Windows users. 👍

Using the `concurrently` is so much better than not having it at all for Windows users as we can't run mutiple npm scripts. 😅

**Comment by jdwilkin4** [comment]
> Mac is using open and Windows is using start.

Yeah, that is why I structured the open command with the OR operator in hopes that it would work for both mac and windows. But it looks like maybe the && might not be working well for windows. 🤔 

maybe this approach would work. This approach removes the 3 second delay in opening the browser

```bash
    "open": "(open http://localhost:4321/) || (start http://localhost:4321/)",
    "dev": "concurrently \"partykit dev\" \"astro dev\" \"npm run open\"",
```
> I tested to copy the same line for start as below
> "start": "(sleep 3 & open http://localhost:4321/) || (timeout /nobreak /t 3 && start http://localhost:4321/)",

I don't think using `start` for this command would work here because technically we are not starting the client and server applications here but instead just opening it on localhost:4321 with a delay. We should probably stick with `open` or another command name that better matches the script 👍

**Comment by jdwilkin4** [comment]
Also, maybe this would work to break it up into windows and mac commands

```bash
    "open-browser:mac": "open http://localhost:4321/",
    "open-browser:windows": "start http://localhost:4321/",
    "dev": "concurrently \"partykit dev\" \"astro dev\" \"npm run open-browser:mac\" \"npm run open-browser:windows\"",
```

**Comment by nickytonline** [comment]
The `dev` command is good in @jdwilkin4 comment above. I wouldn't bother with the `open-browser:*` scripts since we don't want to run both on every OS.

Most are accustomed to clicking on the link in the terminal that shows the URL, but tbh, it's not a hill I want to die on. 😅 There's probably an npm package to open or start depending on the OS if we really want to go that route.

**Comment by jdwilkin4** [comment]
Yeah, that makes sense 👍 

@adiati98 
we will just use this

```bash
 "dev": "concurrently \"partykit dev\" \"astro dev\"",
```
