### ISSUE TITLE
Feature: Upgrade to eslint-plugin 8.x

### ISSUE THREAD

**Issue by nickytonline** [nickytonline/astro-partykit-starter#232]
Dependabot has been trying to update to @typescript-eslint/eslint-plugin from 7.0.0 to 8.x for a while now but the builds always fail. I haven't had a chance to look at this.

This would be a great first issue for anyone interested in TypeScript and ESLint.

**Comment by nickytonline** [comment]
Thanks for taking this one on as well @lmac-1!

**Comment by lmac-1** [comment]
.take 

no problem :)
