### ISSUE TITLE
chore: add rest of team to the CODEOWNERS file

### ISSUE THREAD

**Issue by nickytonline** [nickytonline/astro-partykit-starter#24]
Currently, I'm the only one in the CODEOWNERS file. Why add others to the CODEOWNERS file?

Read about it in my post, [Supercharge your Repository with Code Owners](https://dev.to/opensauced/supercharge-your-repository-with-code-owners-4clg).

Here are the current team members to be added:

![CleanShot 2024-01-05 at 09 30 13@2x](https://github.com/nickytonline/astro-partykit-starter/assets/833231/e3a83d7c-c849-4265-9d8d-8a355110080b)

Anyone on the core team can pick up this issue.

**Comment by adiati98** [comment]
@nickytonline a quick question here. We now have code owners file. But do you receive any notification whenever a new PR comes in? Because I don't receive any, unless someone adds me manually as a reviewer.

**Comment by nickytonline** [comment]
> @nickytonline a quick question here. We now have code owners file. But do you receive any notification whenever a new PR comes in? Because I don't receive any, unless someone adds me manually as a reviewer.

It should add you as a reviewer, but let me check the repo settings.

**Comment by adiati98** [comment]
> > @nickytonline a quick question here. We now have code owners file. But do you receive any notification whenever a new PR comes in? Because I don't receive any, unless someone adds me manually as a reviewer.
> 
> It should add you as a reviewer, but let me check the repo settings.

I'm not sure if this is the case. But I think the reason that it doesn't add us as reviewers is because we miss the asterisk before the name.
For example, `* @adiati98`.

Here is the link to [Example of a CODEOWNERS file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file) on GH docs.

**Comment by nickytonline** [comment]
Hmm, I'm not sure because we don't have `*` on open-sauced repos, and it seems to work fine. I'm pretty busy at the moment, but could you try testing out digging into this with one or more of the other maintainers?

Thanks Ayu!

**Comment by adiati98** [comment]
I'll work on this some time next week as the whole house is sick atm. 😅

But I think, this might need to merge the PR to test it out.
If it doesn't work, I'll create another PR to revert it. 👍

**Comment by Satoshi-Sh** [comment]
Thanks for checking this, @adiati98 !!
