### ISSUE TITLE
Bug: The default username if none is specified is incorrect.

### ISSUE THREAD

**Issue by nickytonline** [nickytonline/astro-partykit-starter#3]
**Describe the bug**

This code was a copy and paste error when I set up the project.

```typescript
const username =
  Astro.url.searchParams.get("username") ??
  "astro-partykit-room" ??
  "Anonymous";
```

**Expected behavior**

It should be

```typescript
const username =
  Astro.url.searchParams.get("username") ?? "anonymous";
```

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nickytonline** [comment]
See these lines of code, https://github.com/nickytonline/astro-partykit-starter/blob/53ea0fb3aeb44a065fdcb196b41c911e6b90cb5f/src/pages/chat/index.astro#L5-L8

And this is the change required.

```diff
- const username =
+ const username = Astro.url.searchParams.get("username") ?? "anonymous";
-  Astro.url.searchParams.get("username") ??
-  "astro-partykit-room" ??
-  "Anonymous";
```

**Comment by heysolomon** [comment]
Hey @nickytonline can I jump on this?

**Comment by Aduwoayooluwa** [comment]
> Hey @nickytonline can I jump on this?

Wanted to just ask about this too now too😅

**Comment by nickytonline** [comment]
Just tread the info in this comment. To self assign it. https://github.com/nickytonline/astro-partykit-starter/issues/3#issuecomment-1869595581

**Comment by heysolomon** [comment]
> Just read the info in this comment to self assign it @heysolomon.
> 
> [#3 (comment)](https://github.com/nickytonline/astro-partykit-starter/issues/3#issuecomment-1869595581)

.take
