### ISSUE TITLE
Add Leave a room Button to Chat Room

### ISSUE THREAD

**Issue by Satoshi-Sh** [nickytonline/astro-partykit-starter#31]
## Is your feature request related to a problem? Please describe.
In the chat room, the application doesn't have a link to go back to home. It would be nice to have a link to leave a room.

## Describe the solution you'd like

Please add `<a href="/" class="bg-red-500 hover:bg-red-700 w-36 mx-auto text-white font-bold py-2 px-4 rounded">Leave a room</a>` to the src/pages/chat/index.astro file. It will look like this after.
```
<div class="grid place-content-center">
      <h1 class="text-center">Astro 🚀 🤝 Partykit 🎈</h1>
      <Party username={username} roomId={roomId} client:load />
      <a href="/" class="bg-red-500 hover:bg-red-700 w-36 mx-auto text-white font-bold py-2 px-4 rounded">Leave a room</a>
    </div>
```
![Screenshot from 2024-01-08 09-25-40](https://github.com/nickytonline/astro-partykit-starter/assets/73622805/96e83b49-c2f1-4495-bc96-6017fd0728a6)

**Comment by nickytonline** [comment]
Would you like to work on this @Satoshi-Sh?

**Comment by Satoshi-Sh** [comment]
I leave it for someone else.

**Comment by Satoshi-Sh** [comment]
I just updated the issue. @nickytonline

**Comment by jdwilkin4** [comment]
Hey @nickytonline ! 

I would be interested in working on this

**Comment by nickytonline** [comment]
> Hey @nickytonline ! 
> 
> 
> 
> I would be interested in working on this

All you're @jdwilkin4!
