### ISSUE TITLE
Duplicate Key Warning

### ISSUE THREAD

**Issue by Satoshi-Sh** [nickytonline/astro-partykit-starter#32]
### src/components/Party.tsx
```
 <ul className="my-4 grid gap-2">
        {messages.map(({ user, text }) => (
          <li key={`${user}_${text}`} className="flex gap-2">
            <span className="font-bold">{user}:</span>
            <span>{text}</span>
          </li>
        ))}
      </ul>
```
The key will be the same if someone sends the same message twice.

## Steps to reproduce

1. Go to the chat room. 
2. Send the same message like "Hello" twice.
3. You will see the duplicate key warning in the browser console.
## Expected behavior
Get no warnings.

## Possible Solution
Add index to the key.

## Screenshots

![Screenshot from 2024-01-08 09-36-18](https://github.com/nickytonline/astro-partykit-starter/assets/73622805/2af0e4b9-07d7-41c9-8246-f5239bc0fb73)

**Comment by Arol15** [comment]
.take

**Comment by DevJSter** [comment]
.take
