### ISSUE TITLE
Feature: add Vitest to the project

### ISSUE THREAD

**Issue by nickytonline** [nickytonline/astro-partykit-starter#40]
Add Vitest to the project, so that the starter kit has a testing framework in place.

Things to be done:
- Install [Vitest](https://vitest.dev/)
- For the vitest.config.ts file, see the [Astro docs for configuring Vitest](https://dev.to/opensauced/migrating-from-jest-to-vitest-for-your-react-application-1b75)
- Create one dummy test
- Add a step to run vitest in lint-staged for code files. See https://github.com/nickytonline/astro-partykit-starter/blob/c8fcfeb7624dd43a7259e7a221992decfbedf209/package.json#L42-L45
- Here's an example config for running it in lint-staged. https://github.com/open-sauced/app/blob/f9ea05308ec63d110a30cb8ada3b195fd3798ffc/package.json#L161

**Comment by adiati98** [comment]
Love the idea of adding a test!
Just out of curiosity, @nickytonline, is there any reason to choose Vitest instead of Playwright or anything else?

Also, I always want to learn about test. I'm interested in working on this, but it might take me some time 😅
So, if it does have a tight deadline, I'll pass it to someone else. 😊

**Comment by nickytonline** [comment]
Playwright is for end to end tests and component tests. Vitest is like Jest, for writing unit tests, and component tests (if not testing components in Playwright).

**Comment by jdwilkin4** [comment]
> So, if it does have a tight deadline, I'll pass it to someone else

It doesn't seem like there is a tight deadline here so you should work on it @adiati98 if you are interested 😄

**Comment by adiati98** [comment]
> > So, if it does have a tight deadline, I'll pass it to someone else
> 
> It doesn't seem like there is a tight deadline here so you should work on it @adiati98 if you are interested 😄

Thanks, @jdwilkin4! I'll .take it then 😄

**Comment by nickytonline** [comment]
If you need any assistance, happy to help.

**Comment by adiati98** [comment]
> If you need any assistance, happy to help.

I'll let you know! Thanks, Nick.

**Comment by adiati98** [comment]
Hey @nickytonline @jdwilkin4 @Satoshi-Sh,

I've worked on this. And for some reason, I can't push my changes to remote repo. Below is the screenshot of the error.

![error: failed to push some refs](https://github.com/nickytonline/astro-partykit-starter/assets/45172775/23be9e49-24ee-4c4e-9429-c3f2f143f5ca)

I've tried `git push -u origin feat/install-vites`, `git push -u upstream feat/install-vites`, `git pull --rebase upstream main`, and `git pull --rebase origin main`. Nothing works.

Does anyone have similar case? I'm not sure what should I do here.

**Comment by nickytonline** [comment]
Did you fork the repository @adiati98? As a maintainer you don't need to. I see you're using `upstream` as your origin which is why I ask. This doesn't explain the erro though. That error usually means that `feat/install-vites` doesn't exist remotely, i.e. on GitHub.

I also see your using https instead of SSH. Again, I don't think that's the issue, but consider using SSH instead. See https://docs.github.com/en/authentication/connecting-to-github-with-ssh.

Worst case try creating a new branch and see if you end up with the same result.

**Comment by adiati98** [comment]
Thanks, @nickytonline.
After debugging on Slack, I found out that I missed a letter in my branch name when I pushed it. 😅

Now all is good.
